disabled = false
languageCode = "es"
weight = 1
title = "NSStudent blog"

[params]
displayName = "Español"
logo = "img/icon45.png"
secondaryLogo = "img/icon45dark.png"
description = "Blog personal"

[params.author]
name = "NSStudent" 
headline = "Blog"
image = "img/nsstudent-author.jpg"
bio = "Desarrolador de iOS y jugador de ajedrez amateur"
links = [
{ x-twitter = "https://x.com/NSStudent" },
{ github = "https://github.com/NSStudent" },
]