[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "vsDrLqjpkb"
weight = 9998

[[main]]
name = "About me"
pageRef = "about.en.md"
identifier = "vsDrLqjpkt"
weight = 9999

[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[footer]]
none = "none"
